# require 'jekyll'

module TwineChomp
  class Generator < Jekyll::Generator
    def generate(site)
      puts "Look it's a generator"
      # open file generated by twine
      file_in = File.open("pages/mani-pedi-story.html", "r")
      # read lines of file and remove newline characters
      story_in = file_in.readlines.map(&:chomp)
      # close file
      file_in.close
      
      # locate css & body of twine story
      # css is all on one line, we chop off html header script tag
      css = story_in[6][25..]
      
      # story content is reliably (so far) in one place
      twine_story = story_in[10..-4]
      
      # store those as variables to be injected
      site.data['story_css'] = css
      site.data['twine_story'] = twine_story

    end
  end
end